# Generated by Django 4.2.9 on 2024-01-19 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("library", "0005_delete_librarybook"),
        ("book", "0002_alter_book_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="library",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="library.library",
            ),
            preserve_default=False,
        ),
    ]
